import { z } from 'zod';
import { apiObject, openEnum } from '#/core';
import { ThrowableSchema } from './throwable';
import { StackTraceElementSchema } from './stackTraceElement';

export const BadRequestExceptionSchema = apiObject({
  cause: ThrowableSchema.optional(),
  stackTrace: z.array(StackTraceElementSchema).optional(),
  responseStatus: openEnum([
    'OK',
    'CREATED',
    'ACCEPTED',
    'NO_CONTENT',
    'RESET_CONTENT',
    'PARTIAL_CONTENT',
    'MOVED_PERMANENTLY',
    'FOUND',
    'SEE_OTHER',
    'NOT_MODIFIED',
    'USE_PROXY',
    'TEMPORARY_REDIRECT',
    'BAD_REQUEST',
    'UNAUTHORIZED',
    'PAYMENT_REQUIRED',
    'FORBIDDEN',
    'NOT_FOUND',
    'METHOD_NOT_ALLOWED',
    'NOT_ACCEPTABLE',
    'PROXY_AUTHENTICATION_REQUIRED',
    'REQUEST_TIMEOUT',
    'CONFLICT',
    'GONE',
    'LENGTH_REQUIRED',
    'PRECONDITION_FAILED',
    'REQUEST_ENTITY_TOO_LARGE',
    'REQUEST_URI_TOO_LONG',
    'UNSUPPORTED_MEDIA_TYPE',
    'REQUESTED_RANGE_NOT_SATISFIABLE',
    'EXPECTATION_FAILED',
    'INTERNAL_SERVER_ERROR',
    'NOT_IMPLEMENTED',
    'BAD_GATEWAY',
    'SERVICE_UNAVAILABLE',
    'GATEWAY_TIMEOUT',
    'HTTP_VERSION_NOT_SUPPORTED',
  ]).optional(),
  scimErrorType: openEnum([
    'invalidFilter',
    'tooMany',
    'uniqueness',
    'mutability',
    'invalidSyntax',
    'invalidPath',
    'noTarget',
    'invalidValue',
    'invalidVers',
    'sensitive',
  ]).optional(),
  message: z.string().optional(),
  localizedMessage: z.string().optional(),
  suppressed: z.array(ThrowableSchema).optional(),
});

export type BadRequestException = z.infer<typeof BadRequestExceptionSchema>;
