parser: "@typescript-eslint/parser"
extends:
  - "airbnb-typescript/base"
parserOptions:
  ecmaVersion: 2018
  sourceType: "module"
  project: "./tsconfig.lint.json"
plugins:
  - "import"
env:
  node: true
  browser: true
rules:
  "@typescript-eslint/lines-between-class-members": "off"
  "arrow-parens":
    - "error"
    - "as-needed"
  "class-methods-use-this": "off"
  "eol-last": "error"
  "import/no-cycle": "off"
  "import/prefer-default-export": "off"
  "linebreak-style":
    - "error"
    - "unix"
  "lines-between-class-members": "off"
  "max-len": "off"
  "no-trailing-spaces": "error"
  "no-underscore-dangle": "off"
  "padding-line-between-statements":
    - "error"
    - blankLine: "always"
      prev: "*"
      next:
        - "block"
        - "block-like"
        - "cjs-export"
        - "class"
        - "const"
        - "export"
        - "import"
        - "let"
        - "var"
    - blankLine: "always"
      prev:
        - "block"
        - "block-like"
        - "cjs-export"
        - "class"
        - "const"
        - "export"
        - "import"
        - "let"
        - "var"
      next: "*"
    - blankLine: "any"
      prev:
        - "const"
        - "let"
        - "var"
      next:
        - "const"
        - "let"
        - "var"
    - blankLine: "never"
      prev:
        - "import"
      next:
        - "import"
    - blankLine: "always"
      prev:
        - "import"
      next:
        - "export"
    - blankLine: "any"
      prev:
        - "export"
      next:
        - "export"
settings:
  import/parsers:
    "@typescript-eslint/parser":
      - ".ts"
