import { z } from 'zod';

export const JsonNodeSchema = z.object({
  array: z.boolean().optional(),
  bigDecimal: z.boolean().optional(),
  bigInteger: z.boolean().optional(),
  bigIntegerValue: z.number().int().optional(),
  binary: z.boolean().optional(),
  binaryValue: z.array(z.string()).optional(),
  boolean: z.boolean().optional(),
  booleanValue: z.boolean().optional(),
  containerNode: z.boolean().optional(),
  decimalValue: z.number().optional(),
  double: z.boolean().optional(),
  doubleValue: z.number().optional(),
  elements: z.object({}).optional(),
  fieldNames: z.object({}).optional(),
  fields: z.object({}).optional(),
  floatingPointNumber: z.boolean().optional(),
  int: z.boolean().optional(),
  intValue: z.number().int().optional(),
  integralNumber: z.boolean().optional(),
  long: z.boolean().optional(),
  longValue: z.number().int().optional(),
  missingNode: z.boolean().optional(),
  null: z.boolean().optional(),
  number: z.boolean().optional(),
  numberType: z.enum(['INT', 'LONG', 'BIG_INTEGER', 'FLOAT', 'DOUBLE', 'BIG_DECIMAL']).optional(),
  numberValue: z.number().optional(),
  object: z.boolean().optional(),
  pojo: z.boolean().optional(),
  textValue: z.string().optional(),
  textual: z.boolean().optional(),
  valueAsBoolean: z.boolean().optional(),
  valueAsDouble: z.number().optional(),
  valueAsInt: z.number().int().optional(),
  valueAsLong: z.number().int().optional(),
  valueAsText: z.string().optional(),
  valueNode: z.boolean().optional(),
});

export type JsonNode = z.infer<typeof JsonNodeSchema>;
