import { BaseClient } from '@/clients/baseClient.mjs';
import { AnnouncementBanner } from '@/version2/announcementBanner.mjs';
import { ApplicationRoles } from '@/version2/applicationRoles.mjs';
import { AppMigration } from '@/version2/appMigration.mjs';
import { AppProperties } from '@/version2/appProperties.mjs';
import { AuditRecords } from '@/version2/auditRecords.mjs';
import { Avatars } from '@/version2/avatars.mjs';
import { Dashboards } from '@/version2/dashboards.mjs';
import { DynamicModules } from '@/version2/dynamicModules.mjs';
import { Filters } from '@/version2/filters.mjs';
import { FilterSharing } from '@/version2/filterSharing.mjs';
import { GroupAndUserPicker } from '@/version2/groupAndUserPicker.mjs';
import { Groups } from '@/version2/groups.mjs';
import { IssueAttachments } from '@/version2/issueAttachments.mjs';
import { IssueCommentProperties } from '@/version2/issueCommentProperties.mjs';
import { IssueComments } from '@/version2/issueComments.mjs';
import { IssueCustomFieldConfigurationApps } from '@/version2/issueCustomFieldConfigurationApps.mjs';
import { IssueCustomFieldContexts } from '@/version2/issueCustomFieldContexts.mjs';
import { IssueCustomFieldOptions } from '@/version2/issueCustomFieldOptions.mjs';
import { IssueCustomFieldOptionsApps } from '@/version2/issueCustomFieldOptionsApps.mjs';
import { IssueCustomFieldValuesApps } from '@/version2/issueCustomFieldValuesApps.mjs';
import { IssueFieldConfigurations } from '@/version2/issueFieldConfigurations.mjs';
import { IssueFields } from '@/version2/issueFields.mjs';
import { IssueLinks } from '@/version2/issueLinks.mjs';
import { IssueLinkTypes } from '@/version2/issueLinkTypes.mjs';
import { IssueNavigatorSettings } from '@/version2/issueNavigatorSettings.mjs';
import { IssueNotificationSchemes } from '@/version2/issueNotificationSchemes.mjs';
import { IssuePriorities } from '@/version2/issuePriorities.mjs';
import { IssueProperties } from '@/version2/issueProperties.mjs';
import { IssueRemoteLinks } from '@/version2/issueRemoteLinks.mjs';
import { IssueResolutions } from '@/version2/issueResolutions.mjs';
import { Issues } from '@/version2/issues.mjs';
import { IssueSearch } from '@/version2/issueSearch.mjs';
import { IssueSecurityLevel } from '@/version2/issueSecurityLevel.mjs';
import { IssueSecuritySchemes } from '@/version2/issueSecuritySchemes.mjs';
import { IssueTypeProperties } from '@/version2/issueTypeProperties.mjs';
import { IssueTypes } from '@/version2/issueTypes.mjs';
import { IssueTypeSchemes } from '@/version2/issueTypeSchemes.mjs';
import { IssueTypeScreenSchemes } from '@/version2/issueTypeScreenSchemes.mjs';
import { IssueVotes } from '@/version2/issueVotes.mjs';
import { IssueWatchers } from '@/version2/issueWatchers.mjs';
import { IssueWorklogProperties } from '@/version2/issueWorklogProperties.mjs';
import { IssueWorklogs } from '@/version2/issueWorklogs.mjs';
import { JiraExpressions } from '@/version2/jiraExpressions.mjs';
import { JiraSettings } from '@/version2/jiraSettings.mjs';
import { JQL } from '@/version2/jql.mjs';
import { JqlFunctionsApps } from '@/version2/jqlFunctionsApps.mjs';
import { Labels } from '@/version2/labels.mjs';
import { LicenseMetrics } from '@/version2/licenseMetrics.mjs';
import { Myself } from '@/version2/myself.mjs';
import { Permissions } from '@/version2/permissions.mjs';
import { PermissionSchemes } from '@/version2/permissionSchemes.mjs';
import { ProjectAvatars } from '@/version2/projectAvatars.mjs';
import { ProjectCategories } from '@/version2/projectCategories.mjs';
import { ProjectComponents } from '@/version2/projectComponents.mjs';
import { ProjectEmail } from '@/version2/projectEmail.mjs';
import { ProjectFeatures } from '@/version2/projectFeatures.mjs';
import { ProjectKeyAndNameValidation } from '@/version2/projectKeyAndNameValidation.mjs';
import { ProjectPermissionSchemes } from '@/version2/projectPermissionSchemes.mjs';
import { ProjectProperties } from '@/version2/projectProperties.mjs';
import { ProjectRoleActors } from '@/version2/projectRoleActors.mjs';
import { ProjectRoles } from '@/version2/projectRoles.mjs';
import { Projects } from '@/version2/projects.mjs';
import { ProjectTypes } from '@/version2/projectTypes.mjs';
import { ProjectVersions } from '@/version2/projectVersions.mjs';
import { Screens } from '@/version2/screens.mjs';
import { ScreenSchemes } from '@/version2/screenSchemes.mjs';
import { ScreenTabFields } from '@/version2/screenTabFields.mjs';
import { ScreenTabs } from '@/version2/screenTabs.mjs';
import { ServerInfo } from '@/version2/serverInfo.mjs';
import { Status } from '@/version2/status.mjs';
import { Tasks } from '@/version2/tasks.mjs';
import { TimeTracking } from '@/version2/timeTracking.mjs';
import { UiModificationsApps } from '@/version2/uiModificationsApps.mjs';
import { UserProperties } from '@/version2/userProperties.mjs';
import { Users } from '@/version2/users.mjs';
import { UserSearch } from '@/version2/userSearch.mjs';
import { Webhooks } from '@/version2/webhooks.mjs';
import { Workflows } from '@/version2/workflows.mjs';
import { WorkflowSchemeDrafts } from '@/version2/workflowSchemeDrafts.mjs';
import { WorkflowSchemeProjectAssociations } from '@/version2/workflowSchemeProjectAssociations.mjs';
import { WorkflowSchemes } from '@/version2/workflowSchemes.mjs';
import { WorkflowStatusCategories } from '@/version2/workflowStatusCategories.mjs';
import { WorkflowStatuses } from '@/version2/workflowStatuses.mjs';
import { WorkflowTransitionProperties } from '@/version2/workflowTransitionProperties.mjs';
import { WorkflowTransitionRules } from '@/version2/workflowTransitionRules.mjs';

export class Version2Client extends BaseClient {
  announcementBanner = new AnnouncementBanner(this);
  applicationRoles = new ApplicationRoles(this);
  appMigration = new AppMigration(this);
  appProperties = new AppProperties(this);
  auditRecords = new AuditRecords(this);
  avatars = new Avatars(this);
  dashboards = new Dashboards(this);
  dynamicModules = new DynamicModules(this);
  filters = new Filters(this);
  filterSharing = new FilterSharing(this);
  groupAndUserPicker = new GroupAndUserPicker(this);
  groups = new Groups(this);
  issueAttachments = new IssueAttachments(this);
  issueCommentProperties = new IssueCommentProperties(this);
  issueComments = new IssueComments(this);
  issueCustomFieldConfigurationApps = new IssueCustomFieldConfigurationApps(this);
  issueCustomFieldContexts = new IssueCustomFieldContexts(this);
  issueCustomFieldOptions = new IssueCustomFieldOptions(this);
  issueCustomFieldOptionsApps = new IssueCustomFieldOptionsApps(this);
  issueCustomFieldValuesApps = new IssueCustomFieldValuesApps(this);
  issueFieldConfigurations = new IssueFieldConfigurations(this);
  issueFields = new IssueFields(this);
  issueLinks = new IssueLinks(this);
  issueLinkTypes = new IssueLinkTypes(this);
  issueNavigatorSettings = new IssueNavigatorSettings(this);
  issueNotificationSchemes = new IssueNotificationSchemes(this);
  issuePriorities = new IssuePriorities(this);
  issueProperties = new IssueProperties(this);
  issueRemoteLinks = new IssueRemoteLinks(this);
  issueResolutions = new IssueResolutions(this);
  issues = new Issues(this);
  issueSearch = new IssueSearch(this);
  issueSecurityLevel = new IssueSecurityLevel(this);
  issueSecuritySchemes = new IssueSecuritySchemes(this);
  issueTypeProperties = new IssueTypeProperties(this);
  issueTypes = new IssueTypes(this);
  issueTypeSchemes = new IssueTypeSchemes(this);
  issueTypeScreenSchemes = new IssueTypeScreenSchemes(this);
  issueVotes = new IssueVotes(this);
  issueWatchers = new IssueWatchers(this);
  issueWorklogProperties = new IssueWorklogProperties(this);
  issueWorklogs = new IssueWorklogs(this);
  jiraExpressions = new JiraExpressions(this);
  jiraSettings = new JiraSettings(this);
  jql = new JQL(this);
  jqlFunctionsApps = new JqlFunctionsApps(this);
  labels = new Labels(this);
  licenseMetrics = new LicenseMetrics(this);
  myself = new Myself(this);
  permissions = new Permissions(this);
  permissionSchemes = new PermissionSchemes(this);
  projectAvatars = new ProjectAvatars(this);
  projectCategories = new ProjectCategories(this);
  projectComponents = new ProjectComponents(this);
  projectEmail = new ProjectEmail(this);
  projectFeatures = new ProjectFeatures(this);
  projectKeyAndNameValidation = new ProjectKeyAndNameValidation(this);
  projectPermissionSchemes = new ProjectPermissionSchemes(this);
  projectProperties = new ProjectProperties(this);
  projectRoleActors = new ProjectRoleActors(this);
  projectRoles = new ProjectRoles(this);
  projects = new Projects(this);
  projectTypes = new ProjectTypes(this);
  projectVersions = new ProjectVersions(this);
  screens = new Screens(this);
  screenSchemes = new ScreenSchemes(this);
  screenTabFields = new ScreenTabFields(this);
  screenTabs = new ScreenTabs(this);
  serverInfo = new ServerInfo(this);
  status = new Status(this);
  tasks = new Tasks(this);
  timeTracking = new TimeTracking(this);
  uiModificationsApps = new UiModificationsApps(this);
  userProperties = new UserProperties(this);
  users = new Users(this);
  userSearch = new UserSearch(this);
  webhooks = new Webhooks(this);
  workflows = new Workflows(this);
  workflowSchemeDrafts = new WorkflowSchemeDrafts(this);
  workflowSchemeProjectAssociations = new WorkflowSchemeProjectAssociations(this);
  workflowSchemes = new WorkflowSchemes(this);
  workflowStatusCategories = new WorkflowStatusCategories(this);
  workflowStatuses = new WorkflowStatuses(this);
  workflowTransitionProperties = new WorkflowTransitionProperties(this);
  workflowTransitionRules = new WorkflowTransitionRules(this);
}
