import { describe, it, expect } from 'vitest';
import { Version2Client } from '@/version2/index.mjs';
import { AnnouncementBanner } from '@/version2/announcementBanner.mjs';
import { ApplicationRoles } from '@/version2/applicationRoles.mjs';
import { AppMigration } from '@/version2/appMigration.mjs';
import { AppProperties } from '@/version2/appProperties.mjs';
import { AuditRecords } from '@/version2/auditRecords.mjs';
import { Avatars } from '@/version2/avatars.mjs';
import { Dashboards } from '@/version2/dashboards.mjs';
import { DynamicModules } from '@/version2/dynamicModules.mjs';
import { Filters } from '@/version2/filters.mjs';
import { FilterSharing } from '@/version2/filterSharing.mjs';
import { GroupAndUserPicker } from '@/version2/groupAndUserPicker.mjs';
import { Groups } from '@/version2/groups.mjs';
import { IssueAttachments } from '@/version2/issueAttachments.mjs';
import { IssueCommentProperties } from '@/version2/issueCommentProperties.mjs';
import { IssueComments } from '@/version2/issueComments.mjs';
import { IssueCustomFieldConfigurationApps } from '@/version2/issueCustomFieldConfigurationApps.mjs';
import { IssueCustomFieldContexts } from '@/version2/issueCustomFieldContexts.mjs';
import { IssueCustomFieldOptions } from '@/version2/issueCustomFieldOptions.mjs';
import { IssueCustomFieldOptionsApps } from '@/version2/issueCustomFieldOptionsApps.mjs';
import { IssueCustomFieldValuesApps } from '@/version2/issueCustomFieldValuesApps.mjs';
import { IssueFieldConfigurations } from '@/version2/issueFieldConfigurations.mjs';
import { IssueFields } from '@/version2/issueFields.mjs';
import { IssueLinks } from '@/version2/issueLinks.mjs';
import { IssueLinkTypes } from '@/version2/issueLinkTypes.mjs';
import { IssueNavigatorSettings } from '@/version2/issueNavigatorSettings.mjs';
import { IssueNotificationSchemes } from '@/version2/issueNotificationSchemes.mjs';
import { IssuePriorities } from '@/version2/issuePriorities.mjs';
import { IssueProperties } from '@/version2/issueProperties.mjs';
import { IssueRemoteLinks } from '@/version2/issueRemoteLinks.mjs';
import { IssueResolutions } from '@/version2/issueResolutions.mjs';
import { Issues } from '@/version2/issues.mjs';
import { IssueSearch } from '@/version2/issueSearch.mjs';
import { IssueSecurityLevel } from '@/version2/issueSecurityLevel.mjs';
import { IssueSecuritySchemes } from '@/version2/issueSecuritySchemes.mjs';
import { IssueTypeProperties } from '@/version2/issueTypeProperties.mjs';
import { IssueTypes } from '@/version2/issueTypes.mjs';
import { IssueTypeSchemes } from '@/version2/issueTypeSchemes.mjs';
import { IssueTypeScreenSchemes } from '@/version2/issueTypeScreenSchemes.mjs';
import { IssueVotes } from '@/version2/issueVotes.mjs';
import { IssueWatchers } from '@/version2/issueWatchers.mjs';
import { IssueWorklogProperties } from '@/version2/issueWorklogProperties.mjs';
import { IssueWorklogs } from '@/version2/issueWorklogs.mjs';
import { JiraExpressions } from '@/version2/jiraExpressions.mjs';
import { JiraSettings } from '@/version2/jiraSettings.mjs';
import { JQL } from '@/version2/jql.mjs';
import { JqlFunctionsApps } from '@/version2/jqlFunctionsApps.mjs';
import { Labels } from '@/version2/labels.mjs';
import { LicenseMetrics } from '@/version2/licenseMetrics.mjs';
import { Myself } from '@/version2/myself.mjs';
import { Permissions } from '@/version2/permissions.mjs';
import { PermissionSchemes } from '@/version2/permissionSchemes.mjs';
import { ProjectAvatars } from '@/version2/projectAvatars.mjs';
import { ProjectCategories } from '@/version2/projectCategories.mjs';
import { ProjectComponents } from '@/version2/projectComponents.mjs';
import { ProjectEmail } from '@/version2/projectEmail.mjs';
import { ProjectFeatures } from '@/version2/projectFeatures.mjs';
import { ProjectKeyAndNameValidation } from '@/version2/projectKeyAndNameValidation.mjs';
import { ProjectPermissionSchemes } from '@/version2/projectPermissionSchemes.mjs';
import { ProjectProperties } from '@/version2/projectProperties.mjs';
import { ProjectRoleActors } from '@/version2/projectRoleActors.mjs';
import { ProjectRoles } from '@/version2/projectRoles.mjs';
import { Projects } from '@/version2/projects.mjs';
import { ProjectTypes } from '@/version2/projectTypes.mjs';
import { ProjectVersions } from '@/version2/projectVersions.mjs';
import { Screens } from '@/version2/screens.mjs';
import { ScreenSchemes } from '@/version2/screenSchemes.mjs';
import { ScreenTabFields } from '@/version2/screenTabFields.mjs';
import { ScreenTabs } from '@/version2/screenTabs.mjs';
import { ServerInfo } from '@/version2/serverInfo.mjs';
import { Status } from '@/version2/status.mjs';
import { Tasks } from '@/version2/tasks.mjs';
import { TimeTracking } from '@/version2/timeTracking.mjs';
import { UiModificationsApps } from '@/version2/uiModificationsApps.mjs';
import { UserProperties } from '@/version2/userProperties.mjs';
import { Users } from '@/version2/users.mjs';
import { UserSearch } from '@/version2/userSearch.mjs';
import { Webhooks } from '@/version2/webhooks.mjs';
import { Workflows } from '@/version2/workflows.mjs';
import { WorkflowSchemeDrafts } from '@/version2/workflowSchemeDrafts.mjs';
import { WorkflowSchemeProjectAssociations } from '@/version2/workflowSchemeProjectAssociations.mjs';
import { WorkflowSchemes } from '@/version2/workflowSchemes.mjs';
import { WorkflowStatusCategories } from '@/version2/workflowStatusCategories.mjs';
import { WorkflowStatuses } from '@/version2/workflowStatuses.mjs';
import { WorkflowTransitionProperties } from '@/version2/workflowTransitionProperties.mjs';
import { WorkflowTransitionRules } from '@/version2/workflowTransitionRules.mjs';

describe('Version2Client', () => {
  it('should have all required properties instantiated', () => {
    const client = new Version2Client({ host: 'http://localhost:3000' });

    expect(client.announcementBanner).toBeInstanceOf(AnnouncementBanner);
    expect(client.applicationRoles).toBeInstanceOf(ApplicationRoles);
    expect(client.appMigration).toBeInstanceOf(AppMigration);
    expect(client.appProperties).toBeInstanceOf(AppProperties);
    expect(client.auditRecords).toBeInstanceOf(AuditRecords);
    expect(client.avatars).toBeInstanceOf(Avatars);
    expect(client.dashboards).toBeInstanceOf(Dashboards);
    expect(client.dynamicModules).toBeInstanceOf(DynamicModules);
    expect(client.filters).toBeInstanceOf(Filters);
    expect(client.filterSharing).toBeInstanceOf(FilterSharing);
    expect(client.groupAndUserPicker).toBeInstanceOf(GroupAndUserPicker);
    expect(client.groups).toBeInstanceOf(Groups);
    expect(client.issueAttachments).toBeInstanceOf(IssueAttachments);
    expect(client.issueCommentProperties).toBeInstanceOf(IssueCommentProperties);
    expect(client.issueComments).toBeInstanceOf(IssueComments);
    expect(client.issueCustomFieldConfigurationApps).toBeInstanceOf(IssueCustomFieldConfigurationApps);
    expect(client.issueCustomFieldContexts).toBeInstanceOf(IssueCustomFieldContexts);
    expect(client.issueCustomFieldOptions).toBeInstanceOf(IssueCustomFieldOptions);
    expect(client.issueCustomFieldOptionsApps).toBeInstanceOf(IssueCustomFieldOptionsApps);
    expect(client.issueCustomFieldValuesApps).toBeInstanceOf(IssueCustomFieldValuesApps);
    expect(client.issueFieldConfigurations).toBeInstanceOf(IssueFieldConfigurations);
    expect(client.issueFields).toBeInstanceOf(IssueFields);
    expect(client.issueLinks).toBeInstanceOf(IssueLinks);
    expect(client.issueLinkTypes).toBeInstanceOf(IssueLinkTypes);
    expect(client.issueNavigatorSettings).toBeInstanceOf(IssueNavigatorSettings);
    expect(client.issueNotificationSchemes).toBeInstanceOf(IssueNotificationSchemes);
    expect(client.issuePriorities).toBeInstanceOf(IssuePriorities);
    expect(client.issueProperties).toBeInstanceOf(IssueProperties);
    expect(client.issueRemoteLinks).toBeInstanceOf(IssueRemoteLinks);
    expect(client.issueResolutions).toBeInstanceOf(IssueResolutions);
    expect(client.issues).toBeInstanceOf(Issues);
    expect(client.issueSearch).toBeInstanceOf(IssueSearch);
    expect(client.issueSecurityLevel).toBeInstanceOf(IssueSecurityLevel);
    expect(client.issueSecuritySchemes).toBeInstanceOf(IssueSecuritySchemes);
    expect(client.issueTypeProperties).toBeInstanceOf(IssueTypeProperties);
    expect(client.issueTypes).toBeInstanceOf(IssueTypes);
    expect(client.issueTypeSchemes).toBeInstanceOf(IssueTypeSchemes);
    expect(client.issueTypeScreenSchemes).toBeInstanceOf(IssueTypeScreenSchemes);
    expect(client.issueVotes).toBeInstanceOf(IssueVotes);
    expect(client.issueWatchers).toBeInstanceOf(IssueWatchers);
    expect(client.issueWorklogProperties).toBeInstanceOf(IssueWorklogProperties);
    expect(client.issueWorklogs).toBeInstanceOf(IssueWorklogs);
    expect(client.jiraExpressions).toBeInstanceOf(JiraExpressions);
    expect(client.jiraSettings).toBeInstanceOf(JiraSettings);
    expect(client.jql).toBeInstanceOf(JQL);
    expect(client.jqlFunctionsApps).toBeInstanceOf(JqlFunctionsApps);
    expect(client.labels).toBeInstanceOf(Labels);
    expect(client.licenseMetrics).toBeInstanceOf(LicenseMetrics);
    expect(client.myself).toBeInstanceOf(Myself);
    expect(client.permissions).toBeInstanceOf(Permissions);
    expect(client.permissionSchemes).toBeInstanceOf(PermissionSchemes);
    expect(client.projectAvatars).toBeInstanceOf(ProjectAvatars);
    expect(client.projectCategories).toBeInstanceOf(ProjectCategories);
    expect(client.projectComponents).toBeInstanceOf(ProjectComponents);
    expect(client.projectEmail).toBeInstanceOf(ProjectEmail);
    expect(client.projectFeatures).toBeInstanceOf(ProjectFeatures);
    expect(client.projectKeyAndNameValidation).toBeInstanceOf(ProjectKeyAndNameValidation);
    expect(client.projectPermissionSchemes).toBeInstanceOf(ProjectPermissionSchemes);
    expect(client.projectProperties).toBeInstanceOf(ProjectProperties);
    expect(client.projectRoleActors).toBeInstanceOf(ProjectRoleActors);
    expect(client.projectRoles).toBeInstanceOf(ProjectRoles);
    expect(client.projects).toBeInstanceOf(Projects);
    expect(client.projectTypes).toBeInstanceOf(ProjectTypes);
    expect(client.projectVersions).toBeInstanceOf(ProjectVersions);
    expect(client.screens).toBeInstanceOf(Screens);
    expect(client.screenSchemes).toBeInstanceOf(ScreenSchemes);
    expect(client.screenTabFields).toBeInstanceOf(ScreenTabFields);
    expect(client.screenTabs).toBeInstanceOf(ScreenTabs);
    expect(client.serverInfo).toBeInstanceOf(ServerInfo);
    expect(client.status).toBeInstanceOf(Status);
    expect(client.tasks).toBeInstanceOf(Tasks);
    expect(client.timeTracking).toBeInstanceOf(TimeTracking);
    expect(client.uiModificationsApps).toBeInstanceOf(UiModificationsApps);
    expect(client.userProperties).toBeInstanceOf(UserProperties);
    expect(client.users).toBeInstanceOf(Users);
    expect(client.userSearch).toBeInstanceOf(UserSearch);
    expect(client.webhooks).toBeInstanceOf(Webhooks);
    expect(client.workflows).toBeInstanceOf(Workflows);
    expect(client.workflowSchemeDrafts).toBeInstanceOf(WorkflowSchemeDrafts);
    expect(client.workflowSchemeProjectAssociations).toBeInstanceOf(WorkflowSchemeProjectAssociations);
    expect(client.workflowSchemes).toBeInstanceOf(WorkflowSchemes);
    expect(client.workflowStatusCategories).toBeInstanceOf(WorkflowStatusCategories);
    expect(client.workflowStatuses).toBeInstanceOf(WorkflowStatuses);
    expect(client.workflowTransitionProperties).toBeInstanceOf(WorkflowTransitionProperties);
    expect(client.workflowTransitionRules).toBeInstanceOf(WorkflowTransitionRules);
  });
});
